/*
 * Work-section project data. Shape mirrors the eventual Sanity PROJECTS_QUERY
 * (title/slug/client/year/role/cover) so swapping to the CMS later is a drop-in.
 * `gallery` is the screenshot list shown in the case-study modal.
 *
 * Covers + gallery shots are the stylised "floating browser card on brand
 * colour" thumbnails generated by scripts/make-thumbs.mjs (public/work/<slug>/).
 * They're faithful brand stand-ins — v1 of the hybrid plan — built to be
 * swapped for real screenshots later without touching the layout, since each is
 * a single 16:9 image (keeps the GSAP Flip cover→modal-hero flight clean).
 */

export interface WorkProject {
	id: string;
	title: string;
	slug: string;
	client: string;
	category: string;
	role: string;
	year: number;
	cover: string;
	gallery: string[];
	description: string;
	liveUrl: string;
}

export const WORK_PROJECTS: WorkProject[] = [
	{
		id: "verifone",
		title: "Verifone",
		slug: "verifone",
		client: "Verifone",
		category: "Payments / Web",
		role: "Design + Development",
		year: 2025,
		cover: "/work/verifone/cover.webp",
		gallery: [
			"/work/verifone/shot-1.webp",
			"/work/verifone/shot-2.webp",
			"/work/verifone/shot-3.webp",
		],
		description:
			"Marketing site for a global payments platform spanning devices, software, and services — a unified system that scales across product lines and 165+ markets without losing clarity.",
		liveUrl: "https://www.verifone.com/",
	},
	{
		id: "buildops",
		title: "BuildOps",
		slug: "buildops",
		client: "BuildOps",
		category: "SaaS / Web",
		role: "Webflow Development",
		year: 2026,
		cover: "/work/buildops/cover.webp",
		gallery: [
			"/work/buildops/shot-1.webp",
			"/work/buildops/shot-2.webp",
			"/work/buildops/shot-3.webp",
		],
		description:
			"A component-first site for an AI-native platform built for commercial contractors — service, projects, and financials in one place, presented to convert demos without burying the product.",
		liveUrl: "https://buildops.com/",
	},
	{
		id: "gainbridge",
		title: "Gainbridge",
		slug: "gainbridge",
		client: "Gainbridge",
		category: "Fintech / Web",
		role: "Design + Development",
		year: 2026,
		cover: "/work/gainbridge/cover.webp",
		gallery: [
			"/work/gainbridge/shot-1.webp",
			"/work/gainbridge/shot-2.webp",
			"/work/gainbridge/shot-3.webp",
		],
		description:
			"A warm, trust-first site that makes a historically opaque product — annuities — feel simple and human: clear rates, plain language, and a calm reading rhythm end to end.",
		liveUrl: "https://gainbridge.com/",
	},
	{
		id: "sharp-performance",
		title: "Sharp Performance",
		slug: "sharp-performance",
		client: "Sharp Performance",
		category: "Brand / Web",
		role: "Design + Development",
		year: 2025,
		cover: "/work/sharp-performance/cover.webp",
		gallery: [
			"/work/sharp-performance/shot-1.webp",
			"/work/sharp-performance/shot-2.webp",
			"/work/sharp-performance/shot-3.webp",
		],
		description:
			"A dark, tactical marketing site for an elite mental-performance coaching practice — built to feel as disciplined as the operators it trains, with motion that earns its restraint.",
		liveUrl: "https://www.sharpperformance.com/",
	},
];

// Lookup by slug — used by the /work/[slug] case-study route (getStaticPaths
// + the page itself). Returns undefined for unknown slugs.
export function getProjectBySlug(slug: string): WorkProject | undefined {
	return WORK_PROJECTS.find((p) => p.slug === slug);
}
