/*
 * Work-section project data. Shape mirrors the eventual Sanity PROJECTS_QUERY
 * (title/slug/client/year/role/cover) so swapping to the CMS later is a drop-in.
 * `gallery` is the screenshot list shown in the case-study modal.
 *
 * Covers + gallery shots are the stylised "floating browser card on brand
 * colour" thumbnails generated by scripts/make-thumbs.mjs (public/work/<slug>/).
 * They're faithful brand stand-ins — v1 of the hybrid plan — built to be
 * swapped for real screenshots later without touching the layout, since each is
 * a single 16:9 image (keeps the GSAP Flip cover→modal-hero flight clean).
 */

export interface WorkProject {
	id: string;
	title: string;
	slug: string;
	client: string;
	category: string;
	role: string;
	year: number;
	cover: string;
	gallery: string[];
	description: string;
	liveUrl: string;
}

export const WORK_PROJECTS: WorkProject[] = [
	{
		id: "verifone",
		title: "Verifone",
		slug: "verifone",
		client: "Verifone",
		category: "Payments / Web",
		role: "Webflow Development",
		year: 2025,
		cover: "/work/verifone/cover.webp",
		gallery: [
			"/work/verifone/shot-1.webp",
			"/work/verifone/shot-2.webp",
			"/work/verifone/shot-3.webp",
		],
		description:
			"I was the lead Webflow developer on Verifone's move off Drupal: 1,000+ pages rebuilt component-first with Lumos, scaling cleanly across 31 locales. CMS-driven navigation and custom JavaScript handle the logic Webflow can't, so the team ships in any market without touching code.",
		liveUrl: "https://www.verifone.com/",
	},
	{
		id: "buildops",
		title: "BuildOps",
		slug: "buildops",
		client: "BuildOps",
		category: "SaaS / Web",
		role: "Webflow Development",
		year: 2026,
		cover: "/work/buildops/cover.webp",
		gallery: [
			"/work/buildops/shot-1.webp",
			"/work/buildops/shot-2.webp",
			"/work/buildops/shot-3.webp",
		],
		description:
			"A component-first build of 60+ components for an AI-native platform serving commercial contractors. Custom JavaScript powers the filtering and a copy-paste HTML library inside rich text, so the client runs everything without meeting the complexity underneath. Migrated 1,000+ blog posts along the way.",
		liveUrl: "https://buildops.com/",
	},
	{
		id: "gainbridge",
		title: "Gainbridge",
		slug: "gainbridge",
		client: "Gainbridge",
		category: "Fintech / Web",
		role: "Webflow Development",
		year: 2026,
		cover: "/work/gainbridge/cover.webp",
		gallery: [
			"/work/gainbridge/shot-1.webp",
			"/work/gainbridge/shot-2.webp",
			"/work/gainbridge/shot-3.webp",
		],
		description:
			"A component-first fintech site where I pivoted to a brand-new design system mid-project, handed over from another agency, without losing momentum. Custom JavaScript keeps a historically opaque product, annuities, manageable through an editor that stays genuinely simple.",
		liveUrl: "https://gainbridge.com/",
	},
	{
		id: "sharp-performance",
		title: "Sharp Performance",
		slug: "sharp-performance",
		client: "Sharp Performance",
		category: "Brand / Web",
		role: "Design + Development",
		year: 2025,
		cover: "/work/sharp-performance/cover.webp",
		gallery: [
			"/work/sharp-performance/shot-1.webp",
			"/work/sharp-performance/shot-2.webp",
			"/work/sharp-performance/shot-3.webp",
		],
		description:
			"A marketing site driven by complex, full-screen section interactions built on fullPage.js and custom JavaScript. Every scroll, transition, and reveal is choreographed by hand for motion that feels intentional, never decorative.",
		liveUrl: "https://www.sharpperformance.com/",
	},
];

// Lookup by slug — used by the /work/[slug] case-study route (getStaticPaths
// + the page itself). Returns undefined for unknown slugs.
export function getProjectBySlug(slug: string): WorkProject | undefined {
	return WORK_PROJECTS.find((p) => p.slug === slug);
}
