/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  email?: string;
  nav?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  socials?: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  skills?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  year?: number;
  role?: Array<string>;
  tags?: Array<string>;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | About
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/lib/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && !(_id in path("drafts.**"))]	| order(featured desc, year desc) {		_id,		title,		"slug": slug.current,		client,		year,		role,		tags,		cover,		featured	}
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  client: string | null;
  year: number | null;
  role: Array<string> | null;
  tags: Array<string> | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  featured: boolean | null;
}>;

// Source: ../src/lib/sanity/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {		_id,		title,		"slug": slug.current,		client,		year,		role,		tags,		cover,		gallery,		body,		links	}
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  client: string | null;
  year: number | null;
  role: Array<string> | null;
  tags: Array<string> | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  links: Array<{
    label?: string;
    url?: string;
    _key: string;
  }> | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../src/lib/sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0] {		bio,		photo,		skills	}
export type ABOUT_QUERY_RESULT = {
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  skills: Array<string> | null;
} | null;

// Source: ../src/lib/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {		title,		description,		nav,		socials,		email	}
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  nav: Array<{
    label?: string;
    href?: string;
    _key: string;
  }> | null;
  socials: Array<{
    platform?: string;
    url?: string;
    _key: string;
  }> | null;
  email: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n\t*[_type == "project" && !(_id in path("drafts.**"))]\n\t| order(featured desc, year desc) {\n\t\t_id,\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\tclient,\n\t\tyear,\n\t\trole,\n\t\ttags,\n\t\tcover,\n\t\tfeatured\n\t}\n': PROJECTS_QUERY_RESULT;
    '\n\t*[_type == "project" && slug.current == $slug][0] {\n\t\t_id,\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\tclient,\n\t\tyear,\n\t\trole,\n\t\ttags,\n\t\tcover,\n\t\tgallery,\n\t\tbody,\n\t\tlinks\n\t}\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n\t*[_type == "project" && defined(slug.current)].slug.current\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n\t*[_type == "about"][0] {\n\t\tbio,\n\t\tphoto,\n\t\tskills\n\t}\n': ABOUT_QUERY_RESULT;
    '\n\t*[_type == "siteSettings"][0] {\n\t\ttitle,\n\t\tdescription,\n\t\tnav,\n\t\tsocials,\n\t\temail\n\t}\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
